cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('newsroom.urls')),
    url(r'', include('gallery.urls')),
    url(r'', include('contact_us.urls')),
)

contact_us/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^contact_us', views.contact_us, name='contact_us'),
]

gallery/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^gallery/(?P<gallery_id>\d+)/(?P<slug>[\w-]+)$', views.gallery, name='gallery'),
    url(r'^gallery', views.gallery_list, name='gallery_list'),
]

newsroom/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<news_id>\d+)/(?P<slug>[\w-]+)$', views.news, name='news'),
    url(r'^$', views.news_list, name='news_list'),
]

contact_us/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from ckeditor.fields import RichTextField
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils.safestring import mark_safe
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


class Gallery(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, default=None)
    image = models.ImageField(upload_to='gallery_images')

    def __str__(self):
        return self.image.url

    def admin_thumbnail(self):
        return mark_safe('<img src="%s" width="150" height="150" />' % (self.image.url))


@receiver(pre_delete, sender=GalleryImage)
def gallery_image_delete(sender, instance, **kwargs):
    if (instance.image):
        instance.image.delete(False)

newsroom/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from ckeditor.fields import RichTextField
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

class News(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    excerpt = models.CharField(max_length=250, default='')
    text = RichTextField()
    image = models.ImageField(upload_to='images', blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def cover(self):
        return '/media/' + self.image.url

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'


@receiver(pre_delete, sender=News)
def news_delete(sender, instance, **kwargs):
    instance.image.delete(False)

contact_us/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.add_input(Submit('submit', _("Send")))

    contact_name = forms.CharField(required=True, label=_("First name"))
    contact_email = forms.EmailField(required=True, label=_("Email"))
    content = forms.CharField(
        required=True,
        widget=forms.Textarea,
        label=_("Message")
    )

contact_us/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

# Create your views here.
def contact_us(request):
    form = ContactForm
    if request.method == 'POST':
        form = form(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name'
                , '')
            contact_email = request.POST.get(
                'contact_email'
                , '')
            form_content = request.POST.get('content', '')

            # Email the profile with the
            # contact information
            template = get_template('contact_us/contact_email.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "Nowa wiadomość",
                content,
                "Your website" + '',
                ['mail@example.org'],
                headers={'Reply-To': contact_email}
            )
            email.send()

            messages.success(request, _('Thanks for contacting us.'))

            return redirect('contact_us')

    return render(request, 'contact_us/index.html', {
        'form': form,
    })

gallery/views.py
from django.shortcuts import render, render_to_response
from django.utils import timezone
from .models import Gallery
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime


# Create your views here.
def gallery_list(request):
    queryset_list = Gallery.objects.all().filter(published_date__lte=datetime.today()).order_by('-published_date')

    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(Q(title__icontains=query))
    else:
        query = ''

    paginator = Paginator(queryset_list, 5)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    get_copy = request.GET.copy()
    parameters = get_copy.pop('page', True) and get_copy.urlencode()

    context = {
        "galleryList": queryset,
        "title": "List",
        "query": query,
        "parameters": parameters
    }

    return render(request, 'gallery/list.html', context)


def gallery(request, gallery_id, slug):
    gallery = Gallery.objects.get(id=gallery_id)
    grid = 3
    if request.GET.get('grid'):
        grid = int(request.GET.get('grid'))
    elif 'grid' in request.session:
        grid = int(request.session['grid'])
    request.session['grid'] = grid

    return render(request, 'gallery/show.html', {'gallery': gallery, 'grid': grid})

newsroom/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import News
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime


def news_list(request):
    queryset_list = News.objects.all().filter(published_date__lte=datetime.today()).order_by('-published_date')

    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(Q(title__icontains=query) | Q(text__icontains=query))
    else:
        query = ''

    paginator = Paginator(queryset_list, 5)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    get_copy = request.GET.copy()
    parameters = get_copy.pop('page', True) and get_copy.urlencode()

    context = {
        "newsList": queryset,
        "title": "List",
        "query": query,
        "parameters": parameters
    }

    return render(request, 'newsroom/list.html', context)


def news(request, news_id, slug):
    news = News.objects.get(id=news_id)

    return render(request, 'newsroom/show.html', {'news': news})

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load stat_tags %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans "Newsroom and galleries" %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'news_list' %}">News-galleries</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'news_list' %}">{% trans "Newsroom" %} <span class="badge">{% total_news %}</span></a>
                </li>
                <li>
                    <a href="{% url 'gallery_list' %}">{% trans "Galleries" %} <span class="badge">{% total_galleries %}</span></a>
                </li>
                <li>
                    <a href="{% url 'contact_us' %}">{% trans "Contact us" %}</a>
                </li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                {% if user.is_staff %}
                    <li>
                        <a href="{% url 'admin:index' %}">{% trans "Dashboard" %}</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'auth_logout' %}">{% trans "Logout" %}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'auth_login' %}">{% trans "Login" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'registration_register' %}">{% trans "Register" %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            {% block content %}
            {% endblock %}
        </div>

        <div class="col-md-4 visible-lg">
            <div class="sidebar-nav-fixed affix pull-right sidebar">
                {% block sidebar %}
                {% endblock %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1>{% trans "Language" %}</h1>
                    </div>
                    <div class="panel-body">
                        <form class="form-inline" action="{% url 'set_language' %}"
                              method="post">{% csrf_token %}
                            <div class="form-group">
                                <input class="form-control" name="next" type="hidden" value="{{ redirect_to }}"/>
                                <select class="form-control" name="language">
                                    {% get_current_language as LANGUAGE_CODE %}
                                    {% get_available_languages as LANGUAGES %}
                                    {% get_language_info_list for LANGUAGES as languages %}
                                    {% for language in languages %}
                                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                                selected="selected"{% endif %}>
                                            {{ language.name_local }} ({{ language.code }})
                                        </option>
                                    {% endfor %}
                                </select>
                                <input class="btn btn-default" type="submit" value="{% trans "Change" %}"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <hr>

    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>&copy; Patryk Antkowiak 113983</p>
            </div>
        </div>
    </footer>
</div>

<!-- jQuery -->
<script src="{% static 'js/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/contact_us/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            {% trans "Contact us!" %}
        </div>
        <div class="panel-body">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endfor %}
                </ul>
            {% endif %}

            <form class="form-horizontal col-md-8 col-md-push-2" action="" method="post" id="contact_form">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock content %}

templates/gallery/base.html
{% extends 'base.html' %}
{% load i18n %}
{% load static from staticfiles %}

{% block css %}
    <link href="{% static 'css/ekko-lightbox.min.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static 'js/ekko-lightbox.min.js' %}"></script>
    <script>
        $(document).on('click', '[data-toggle="lightbox"]', function(event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });
    </script>
{% endblock %}


{% block sidebar %}
    <div class="well">
        <h4>{% trans "Gallery Search" %}</h4>
        <form class="input-group" action="" method="get">
            <input type="text" name="q" class="form-control" value="{{ query }}">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <span class="glyphicon glyphicon-search"></span>{% trans "Search" %}
            </button>
            </span>
        </form>
        <!-- /.input-group -->
    </div>
{% endblock %}

templates/gallery/list.html
{% extends 'gallery/base.html' %}
{% load i18n %}
{% load has_group %}

{% block content %}
    {% for gallery in galleryList %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="{% url 'gallery' gallery_id=gallery.id slug=gallery.title|slugify %}">
                    <h1>{{ gallery.title }}</h1></a>
                <div class="row">
                    <div class="col-md-10">
                        <p><span
                                class="glyphicon glyphicon-time"></span> {{ gallery.published_date }} {% trans "by" %} {{ gallery.author }}
                        </p>
                    </div>
                    <div class="col-md-2 text-right">
                        {% if user|has_group:'Photographer' or user.is_superuser %}
                            <a href="{% url "admin:gallery_gallery_change" gallery.id %}"
                               class="btn btn-default"><span
                                    class="glyphicon glyphicon-edit"></span></a>
                            <a href="{% url "admin:gallery_gallery_delete" gallery.id %}"
                               class="btn btn-danger"><span
                                    class="glyphicon glyphicon-remove"></span></a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="panel-body">
                {% for gallery_image in gallery.galleryimage_set.all|slice:":3" %}
                    <div class="col-md-4">
                        <a href="{{ gallery_image.image.url }}" data-toggle="lightbox"
                           data-gallery="gallery-{{ gallery.id }}">
                            <img src="{{ gallery_image.image.url }}" class="img-responsive cover-img">
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!--<p class="lead">{{ gallery.excerpt|striptags }}</p>-->
    {% endfor %}

    {% if galleryList.has_other_pages %}
        <ul class="pagination">
            {% if galleryList.has_previous %}
                <li><a href="?page={{ galleryList.previous_page_number }}&{{ parameters }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in galleryList.paginator.page_range %}
                {% if galleryList.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}&{{ parameters }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if galleryList.has_next %}
                <li><a href="?page={{ galleryList.next_page_number }}&{{ parameters }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock content %}

templates/gallery/show.html
{% extends 'gallery/base.html' %}
{% load i18n %}
{% load has_group %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>{{ gallery.title }}</h1>
            <div class="row">
                <div class="col-md-8">
                    <p><span class="glyphicon glyphicon-time"></span> {{ gallery.published_date }} {% trans "by" %} {{ gallery.author }}</p>
                </div>
                <div class="col-md-4 text-right">
                    {% if user|has_group:'Photographer' or user.is_superuser %}
                            <a href="{% url "admin:gallery_gallery_change" gallery.id %}"
                               class="btn btn-default"><span
                                    class="glyphicon glyphicon-edit"></span></a>
                            <a href="{% url "admin:gallery_gallery_delete" gallery.id %}"
                               class="btn btn-danger"><span
                                    class="glyphicon glyphicon-remove"></span></a>
                    {% endif %}
                    <form style="display: inline-block" method="get" action="">{% csrf_token %}
                        <button type="submit" class="btn">
                            <span class="glyphicon glyphicon-th"></span>
                        </button>
                        <input type="hidden" name="grid" value="4"/>
                    </form>
                    <form style="display: inline-block" method="get" action="">{% csrf_token %}
                        <button type="submit" class="btn">
                            <span class="glyphicon glyphicon-th-large"></span>
                        </button>
                        <input type="hidden" name="grid" value="3"/>
                    </form>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                {% for gallery_image in gallery.galleryimage_set.all %}
                    <div class="col-md-{% if grid == 4 %}3{% else %}4{% endif %}">
                        <a href="{{ gallery_image.image.url }}" data-toggle="lightbox" data-gallery="gallery-{{ gallery.id }}">
                            <img src="{{ gallery_image.image.url }}" class="img-responsive cover-img">
                        </a>
                    </div>
                    {% if forloop.counter|divisibleby:grid %}
                        </div>
                        <div class="row">
                    {% endif %}
                {% endfor %}
                </div>
            <div class="col-md-8 col-md-push-1 fb-comments"></div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '145635795929329',
                xfbml: true,
                version: 'v2.8'
            });
            FB.AppEvents.logPageView();
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <script>(
        function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.8&appId=145635795929329";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
{% endblock %}

templates/newsroom/base.html
{% extends 'base.html' %}
{% load i18n %}

{% block sidebar %}
    <div class="well">
        <h4>{% trans "News Search" %}</h4>
        <form class="input-group" action="" method="get">
            <input type="text" name="q" class="form-control" value="{{ query }}">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <span class="glyphicon glyphicon-search"></span>{% trans "Search" %}
            </button>
            </span>
        </form>
        <!-- /.input-group -->
    </div>
{% endblock %}

templates/newsroom/list.html
{% extends 'newsroom/base.html' %}
{% load i18n %}
{% load has_group %}

{% block content %}
    {% for news in newsList %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="{% url 'news' news_id=news.id slug=news.title|slugify %}"><h1>{{ news.title }}</h1></a>
                <div class="row">
                    <div class="col-md-10">
                        <p><span
                                class="glyphicon glyphicon-time"></span> {{ news.published_date }} {% trans "by" %} {{ news.author }}
                        </p>
                    </div>
                    <div class="col-md-2 text-right">
                        {% if user|has_group:'Newsman' or user.is_superuser %}
                            <a href="{% url "admin:newsroom_news_change" news.id %}"
                               class="btn btn-default"><span
                                    class="glyphicon glyphicon-edit"></span></a>
                            <a href="{% url "admin:newsroom_news_delete" news.id %}"
                               class="btn btn-danger"><span
                                    class="glyphicon glyphicon-remove"></span></a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="panel-body">
                {% if news.image %}
                    <img class="cover-img" src="{{ news.image.url }}" alt="">
                {% endif %}
                <hr>
                <p class="lead">{{ news.excerpt|striptags }}</p>
            </div>
        </div>
    {% endfor %}

    {% if newsList.has_other_pages %}
        <ul class="pagination">
            {% if newsList.has_previous %}
                <li><a href="?page={{ newsList.previous_page_number }}&{{ parameters }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in newsList.paginator.page_range %}
                {% if newsList.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}&{{ parameters }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if newsList.has_next %}
                <li><a href="?page={{ newsList.next_page_number }}&{{ parameters }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock content %}

templates/newsroom/show.html
{% extends 'newsroom/base.html' %}
{% load i18n %}
{% load has_group %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>{{ news.title }}</h1>
            <div class="row">
                <div class="col-md-10">
                    <p><span
                            class="glyphicon glyphicon-time"></span> {{ news.published_date }} {% trans "by" %} {{ news.author }}
                    </p>
                </div>
                <div class="col-md-2 text-right">
                    {% if user|has_group:'Newsman' or user.is_superuser %}
                        <a href="{% url "admin:newsroom_news_change" news.id %}"
                           class="btn btn-default"><span
                                class="glyphicon glyphicon-edit"></span></a>
                            <a href="{% url "admin:newsroom_news_delete" news.id %}"
                               class="btn btn-danger"><span
                                    class="glyphicon glyphicon-remove"></span></a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="panel-body">
            {% if news.image %}
                <img class="cover-img" src="{{ news.image.url }}" alt="">
            {% endif %}
            <hr>
            <p class="lead">{{ news.text|safe }}</p>
            <div class="col-md-8 col-md-push-1 fb-comments"></div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '145635795929329',
                xfbml: true,
                version: 'v2.8'
            });
            FB.AppEvents.logPageView();
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <script>(
        function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.8&appId=145635795929329";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
{% endblock %}